name: mad_activity12
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

# Environment
environment:
  sdk: ^3.5.2

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # Firebase packages for Firestore and initialization
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  
  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Recommended lints for good coding practices
  flutter_lints: ^4.0.0

flutter:
  # Use material design icons
  uses-material-design: true
